apiVersion: v1
kind: Service
metadata:
  name: front-service
spec:
  selector:
    app: front-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30517